### ISSUE TITLE
consider more signals (such as attributes) in the matching quotient

### ISSUE THREAD

**Issue by crislin2046** [crislin2046/selector-generalization#8]
such as other attributes, like src, href, type
 value, aria-role, itemprop, maybe data- and so on
 and some way to handle it in the algorithm

we already do id, class, tag and nth-of-type 
but we could add more :D

**Comment by dosyago-coder-0** [comment]
We could even add information from things like

computed style (wow) to be able to match things styled similarly

Wow

**Comment by dosyago-coder-0** [comment]
like name attribute is a good one I think, maybe role, itemprop, itemref, itemtype are good attributes to include as well
